plugins {
    alias(libs.plugins.android.lib)
    id("com.myapplication.android.builder")
}

android {
    namespace = "com.example.hostconfig"

    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        buildConfigField("String", "HOST", "String.valueOf(\"https://api.example.com\")")
    }
}
